POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=----MyBoundary

----MyBoundary
Content-Disposition: form-data; name="title"

My cat
----MyBoundary
Content-Disposition: form-data; name="user_id"

1
----MyBoundary
Content-Disposition: form-data; name="file"; filename="cat-pic1.jpg"
Content-Type: image/jpeg

< ./public/cat-pic1.jpg
----MyBoundary--