### Login oikealla salasanalla
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "juha",
  "password": "salasana"
}

### Login väärällä salasanalla
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "juha",
  "password": "salasana-väärä"
}

### Post login
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "username": "JohnDoe",
  "password": "to-be-hashed-pw1"
}

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer .